name: coreutils

environment:
  sdk: '^3.5.0'

dependencies:  
  ffi: ^2.1.3
  win32: any
  ffigen: ^14.0.1

#dart run ffigen.
ffigen:
  llvm-path: 
  - 'C:\llvm'    
  output: 'generated_bindings.dart'
  headers:
    entry-points:
      - 'bin/teste_c.h'
    include-directives:    
    - 'C:/Program Files/JetBrains/CLion 2024.2.2/bin/mingw/x86_64-w64-mingw32/include/**'  
